### ISSUE TITLE
[META] rewire event handling for components

### ISSUE THREAD

**Issue by stopfstedt** [ilios/common#2041]
passing event handlers directly now throws a template linter error. it's relatively easy to work around this.

- [x] `SortableHeader` component - replace `@click` with `@onClick`
- [x] `SortableTh` component - replace `@click` with `@onClick`
- [x] `DatePicker` component - replace `@change` with `@onChange`

for reference, see https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-passed-in-event-handlers.md

**Comment by stopfstedt** [comment]
there are probably others that need this treatment, update the list above as those get identified.
